-- +migrate Up

ALTER TABLE `app_config`
    ADD COLUMN ip_white_list VARCHAR(1000) null default '127.0.0.1,localhost' COMMENT '后台IP白名单',
    ADD COLUMN login_type smallint null default 4 COMMENT 'app登录类型：1-用户名+密码，2-手机号+密码，3-用户名+密码+手机号+密码，4-自动注册登录模式',
    ADD COLUMN sensitive_words text null COMMENT '敏感词，多个敏感词用英文的 | 符号分割',
    ADD COLUMN disable_change_device smallint null default 0 COMMENT '是否禁止更换设备: 1 禁止、0 不禁止',
    ADD COLUMN signup_device_limit smallint null default 0 COMMENT '设备限制注册限制数, 0为不限制',
    ADD COLUMN sigle_ip_register_limit_in_12hour smallint null default 0 COMMENT '单IP12小时注册限制数, 0为不限制',
    ADD COLUMN auto_clear_history_msg smallint null default 0 COMMENT '自动清除几天前历史消息, 0 不自动清除',
    ADD COLUMN charge_and_payout_visible smallint null default 1 COMMENT '充值和提现是否可见',
    ADD COLUMN signin_auth_code_visible smallint null default 1 COMMENT '登录授权码是否可见',
    ADD COLUMN friend_online_status_visible smallint null default 1 COMMENT '好友在线状态是否可见',
    ADD COLUMN mobile_msg_read_status_visible smallint null default 1 COMMENT '手机消息已读状态是否可见',
    ADD COLUMN wallet_payout_min smallint null default 0 COMMENT '钱包提现最小金额，单位为分，0为不限制',
    ADD COLUMN transfer_min_amount smallint null default 0 COMMENT '转账最小金额，单位为分，0为不限制',
    ADD COLUMN mobile_edit_msg smallint null default 1 COMMENT '手机端是否可以编辑消息',
    ADD COLUMN group_member_see_member smallint null default 1 COMMENT '普通群成员是否可以查看其他群成员',
    ADD COLUMN msg_time_visible smallint null default 1 COMMENT '消息时间是否可见',
    ADD COLUMN pinned_conversation_sync smallint null default 1 COMMENT '置顶会话是否同步',
    ADD COLUMN only_internal_friend_add smallint null default 0 COMMENT '仅内部号可被加好友及加非内部号好友',
    ADD COLUMN only_internal_friend_create_group smallint null default 0 COMMENT '仅内部号可建群',
    ADD COLUMN only_internal_friend_send_group_red_envelope smallint null default 0 COMMENT '仅内部号可发群红包',
    ADD COLUMN only_internal_friend_send_group_card smallint null default 0 COMMENT '仅内部号可群内推送名片',
    ADD COLUMN only_internal_friend_group_robot_free_msg smallint null default 0 COMMENT '群机器人免消息',
    ADD COLUMN group_member_limit smallint null default 0 COMMENT '群人数限制: 0 不限制',
    ADD COLUMN user_agreement_content text null COMMENT '用户协议内容',
    ADD COLUMN privacy_policy_content text null COMMENT '隐私政策内容';